# Generated by Django 4.0.4 on 2022-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pics1',
            new_name='pic1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pics2',
            new_name='pic2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pics3',
            new_name='pic3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pics4',
            new_name='pic4',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pin',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
