# Generated by Django 4.0.4 on 2022-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='POD', max_length=20),
        ),
    ]
