# Generated by Django 4.0.4 on 2022-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_checkout_rpoid_alter_checkout_rppid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rpoid',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rppid',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rpsid',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
