# Generated by Django 4.0.4 on 2022-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_contact_name_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Resolved')], default=1),
        ),
    ]
